[versions]
navigation = "2.7.7"
camera = "1.3.4"

[libraries]
activity = { module = "androidx.activity:activity", version = "1.9.0" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version = "1.6.2" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigation" }
multidex = { module = "androidx.multidex:multidex", version = "2.0.1" }
test-ext-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "camera" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "camera" }

[bundles]
navigation = ["navigation-fragment", "navigation-ui"]
camera = ["camera-camera2", "camera-extensions", "camera-lifecycle", "camera-view"]

[plugins]
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }