[versions]
navigation = "2.7.7"
camera = "1.3.2"

[libraries]
activity-ktx = { module = "androidx.activity:activity-ktx", version = "1.8.2" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version = "1.6.2" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
multidex = { module = "androidx.multidex:multidex", version = "2.0.1" }
test-ext-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "camera" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "camera" }

[bundles]
navigation = ["navigation-fragment-ktx", "navigation-ui-ktx"]
camera = ["camera-camera2", "camera-extensions", "camera-lifecycle", "camera-view"]

[plugins]
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }